#!/usr/bin/env ruby
repo_dir = File.expand_path(File.dirname(__FILE__))
Dir.chdir(repo_dir)

def verbose(command)
  puts "--> #{command}"
  system(command) or raise("Failed: #{command}")
end

verbose('jslint --indent 2 --sloppy --stupid --evil reverb.js')
verbose('uglifyjs reverb.js --compress > reverb.min.js')

demo = File.read('demo.html')

generated = "<!--BEGIN GENERATED-->\n"
Dir.glob('Library/*.wav') {|file|
  url = 'https://rawgit.com/burnson/Reverb.js/master/' + file + '.base64'
  name = File.basename(file, File.extname(file))
  description = File.read('Library/' + name + '.attribution.txt')
  x = ''
  x += "<h1>#{name} "
  x += '<a href="javascript:testReverb('
  x += "'#{url}'"
  x += ');">'
  x += "(listen)"
  x += "</a></h1>\n"
  x += "<h2>Attribution</h2>"
  x += "<p>"
  x += description.gsub("\n", "<br/>") + "\n"
  x += "</p>\n"
  x += "<h2>Usage</h2>\n"
  x += "<pre>"
  x += "var audioContext = (your audio context);\n"
  x += "reverbjs.extend(audioContext);\n"
  x += "var reverbUrl = \"#{url}\";\n"
  x += "var reverbNode = audioContext.createReverbFromBase64Url(reverbUrl, function() {\n"
  x += "  console.log(\"Loaded reverb \" + reverbUrl);\n"
  x += "});\n"
  x += "reverbNode.connect(audioContext.destination);\n"
  x += "(some source node).connect(reverbNode);\n"
  x += "</pre>\n"
  generated += x
}
generated += "<!--END GENERATED-->"
reverbjs = "<!--BEGIN REVERBJS-->\n"
reverbjs += "<script type=\"text/javascript\">\n"
reverbjs += File.read('reverb.js')
reverbjs += "</script>"
reverbjs += "<!--END REVERBJS-->"

demo = demo.gsub(/[<].--BEGIN GENERATED.*END GENERATED--[>]/m) {generated}
demo = demo.gsub(/[<].--BEGIN REVERBJS.*END REVERBJS--[>]/m) {reverbjs}
File.write('demo.html', demo)