#!/usr/bin/env ruby

repo_dir = File.expand_path(File.dirname(__FILE__))

if ARGV.length < 1
  puts 'Usage: import_impulse_response [ir-audio-file] ...'
  exit
end

def verbose(command)
  puts "--> #{command}"
  system(command)
end

ARGV.each do |in_file|
  name = File.basename(in_file, File.extname(in_file))

  wav = "#{repo_dir}/Library/#{name}.wav"
  wav_base64 = "#{repo_dir}/Library/#{name}.wav.base64"
  m4a = "#{repo_dir}/Library/#{name}.m4a"
  m4a_base64 = "#{repo_dir}/Library/#{name}.m4a.base64"
  attribution = "#{repo_dir}/Library/#{name}.attribution.txt"

  # First normalize the input into 16-bit, stereo, 44.1KHz, PCM.
  verbose("rm -f #{wav}")
  verbose("ffmpeg -v quiet -i #{in_file} -ac 2 -ar 44100 #{wav}")

  # Now create the AAC-encoded M4A version.
  verbose("rm -f #{m4a}")
  verbose("afconvert #{wav} -o #{m4a} -f m4af")

  # Create base64 versions of above files.
  verbose("openssl base64 -A -in #{wav} > #{wav_base64}")
  verbose("openssl base64 -A -in #{m4a} > #{m4a_base64}")

  # Touch the attribution file.
  verbose("touch #{attribution}")
end
